# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# 将 StereoProjectParams 转换成可以序列化的格式
class StereoProjectParams(object):
    def __init__(self, project_dis, project_size, theta_rotate=0):
        self.project_dis = project_dis
        self.project_size = project_size
        self.theta_rotate = theta_rotate

    def __str__(self):
        return "project_dis: %f, project_size: %f, theta_rotate: %f" % (
            self.project_dis, self.project_size, self.theta_rotate)

    def SerializeToString(self):
        return self.__str__()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x64\x65tect.proto\x12\x0epano_detection\"w\n\x10YoloModelRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x12\n\nimage_size\x18\x02 \x01(\x03\x12\x14\n\x0cweights_path\x18\x04 \x01(\t\x12\x12\n\nconf_thres\x18\x05 \x01(\x01\x12\x11\n\tiou_thres\x18\x06 \x01(\x01\"f\n\x0f\x44\x65tectResultBBX\x12\x0c\n\x04xmin\x18\x01 \x01(\x03\x12\x0c\n\x04ymin\x18\x02 \x01(\x03\x12\x0c\n\x04xmax\x18\x03 \x01(\x03\x12\x0c\n\x04ymax\x18\x04 \x01(\x03\x12\r\n\x05label\x18\x05 \x01(\x03\x12\x0c\n\x04\x63onf\x18\x06 \x01(\x01\"h\n\x11YoloModelResponse\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12?\n\x16\x64\x65tect_result_bbx_list\x18\x02 \x03(\x0b\x32\x1f.pano_detection.DetectResultBBX2_\n\x0c\x44\x65\x66ormYolov5\x12O\n\x06\x44\x65tect\x12 .pano_detection.YoloModelRequest\x1a!.pano_detection.YoloModelResponse\"\x00\x62\x06proto3')

_YOLOMODELREQUEST = DESCRIPTOR.message_types_by_name['YoloModelRequest']
_DETECTRESULTBBX = DESCRIPTOR.message_types_by_name['DetectResultBBX']
_YOLOMODELRESPONSE = DESCRIPTOR.message_types_by_name['YoloModelResponse']
YoloModelRequest = _reflection.GeneratedProtocolMessageType('YoloModelRequest', (_message.Message,), {
    'DESCRIPTOR': _YOLOMODELREQUEST,
    '__module__': 'detect_pb2'
    # @@protoc_insertion_point(class_scope:pano_detection.YoloModelRequest)
})
_sym_db.RegisterMessage(YoloModelRequest)

DetectResultBBX = _reflection.GeneratedProtocolMessageType('DetectResultBBX', (_message.Message,), {
    'DESCRIPTOR': _DETECTRESULTBBX,
    '__module__': 'detect_pb2'
    # @@protoc_insertion_point(class_scope:pano_detection.DetectResultBBX)
})
_sym_db.RegisterMessage(DetectResultBBX)

YoloModelResponse = _reflection.GeneratedProtocolMessageType('YoloModelResponse', (_message.Message,), {
    'DESCRIPTOR': _YOLOMODELRESPONSE,
    '__module__': 'detect_pb2'
    # @@protoc_insertion_point(class_scope:pano_detection.YoloModelResponse)
})
_sym_db.RegisterMessage(YoloModelResponse)

_DEFORMYOLOV5 = DESCRIPTOR.services_by_name['DeformYolov5']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _YOLOMODELREQUEST._serialized_start = 32
    _YOLOMODELREQUEST._serialized_end = 151
    _DETECTRESULTBBX._serialized_start = 153
    _DETECTRESULTBBX._serialized_end = 255
    _YOLOMODELRESPONSE._serialized_start = 257
    _YOLOMODELRESPONSE._serialized_end = 361
    _DEFORMYOLOV5._serialized_start = 363
    _DEFORMYOLOV5._serialized_end = 458
# @@protoc_insertion_point(module_scope)
